from setuptools import setup, find_namespace_packages

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_scriptqueue",
    description="A Commandable SAL Component (CSC) that runs Python scripts..",
    use_scm_version={
        "write_to": "python/lsst/ts/scriptqueue/version.py",
        "write_to_template": scm_version_template,
    },
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    scripts=[
        "bin/command_script_queue.py",
        "bin/run_one_script.py",
        "bin/run_script_queue.py",
    ],
    license="GPL",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_observatory_control",
    },
)
